import './globals.css';
import { Inter } from 'next/font/google';
import Navbar from './navbar/Navbar';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const mode = cookies().get('mode')?.value ?? 'light';

  return (
    <html lang="en">
      <body className={`inter.className ${mode === 'light' ? '' : 'dark-mode'}`}>
        <Navbar mode={mode} />
        {children}
      </body>
    </html>
  );
}
